DecisionTreeRegressor:
  max_depth:   #None
  max_features:   #None
  max_leaf_nodes:   #None
  min_impurity_decrease: 0.0  # Adjusted within the valid range
  min_samples_leaf: 1  # Adjusted within the valid range
  min_samples_split: 5  # Adjusted within the valid range
  splitter: 'best'


